name: Push/PR pipeline
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    # Should be just:
    # uses: ./.github/workflows/build.reusable.yml
    # but https://github.com/github/feedback/discussions/10679
    uses: newrelic/nri-kubernetes/.github/workflows/build.reusable.yml@ci/reusable-workflows
    with:
      upload: true
      artifact: nri-kubernetes-${{ github.sha }}

  build-container:
    # Should be just:
    # uses: ./.github/workflows/build.reusable.yml
    # but https://github.com/github/feedback/discussions/10679
    uses: newrelic/nri-kubernetes/.github/workflows/container.reusable.yml@ci/reusable-workflows
    needs: [ build ]
    with:
      name: ghcr.io/newrelic/nri-kubernetes
      tag: ${{ github.head_ref }}
      artifact: nri-kubernetes-${{ github.sha }}

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: make test

  static-analysis:
    name: Static analysis and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: newrelic/newrelic-infra-checkers@v1
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          auditOn: push
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        continue-on-error: ${{ github.event_name != 'pull_request' }}
        with:
          only-new-issues: true

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Codespell test
        uses: codespell-project/actions-codespell@master
